language: node_js
node_js:
  - 14
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - yarn lint
  - yarn test:coveralls
  - yarn test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: course-fordevs-react
  skip_cleanup: true
notifications:
  email: false
